//! Memory-mapped register access for the Rockchip NPU.
//!
//! The raw register-block types come from the `rknpu_regs` crate generated by
//! `svd2rust`. This module wraps a dynamic MMIO base address in [`RknpuCore`]
//! and exposes typed register-block accessors plus submit and IRQ helpers.
use crate::ioctrl::RknpuSubmit;
use core::ptr::NonNull;
use core::sync::atomic::{AtomicU32, Ordering};

use alloc::sync::Arc;
use mbarrier::mb;

use crate::{JobMode, RknpuError, Submit, SubmitRef, data::RknpuData};

use crate::RknpuTask;
use crate::SubmitBase;
use core::hint::spin_loop;

const INT_CLEAR_ALL: u32 = 0x1_FFFF;
const RKNPU_PC_DATA_EXTRA_AMOUNT: u32 = 4;
const PC_BASE_ADDRESS_OFFSET: u16 = 0x0010;
const PC_INTERRUPT_MASK_OFFSET: u16 = 0x0020;
const PC_TASK_CON_OFFSET: u16 = 0x0030;
const PC_task_array_dma_address_ADDR_OFFSET: u16 = 0x0034;
const PC_INTERRUPT_STATUS_OFFSET: u16 = 0x0028;
const PC_INTERRUPT_RAW_STATUS_OFFSET: u16 = 0x002c;
const PC_TASK_STATUS_OFFSET: u16 = 0x003c;
const DPU_RDMA_S_POINTER_OFFSET: u16 = 0x5004;
const PPU_S_POINTER_OFFSET: u16 = 0x6004;
const PPU_RDMA_S_POINTER_OFFSET: u16 = 0x7004;
const CNA_OPERATION_ENABLE_OFFSET: u16 = 0x1008;
const CORE_OPERATION_ENABLE_OFFSET: u16 = 0x3008;
const DPU_OPERATION_ENABLE_OFFSET: u16 = 0x4008;
const DPU_RDMA_OPERATION_ENABLE_OFFSET: u16 = 0x5008;
const PPU_OPERATION_ENABLE_OFFSET: u16 = 0x6008;
const PPU_RDMA_OPERATION_ENABLE_OFFSET: u16 = 0x7008;
const GLOBAL_OPERATION_ENABLE_OFFSET: u16 = 0xf008;

#[derive(Clone)]
/// Immutable view of one NPU core's MMIO register window.
///
/// # Interrupt-driven completion
///
/// Each core owns a shared `irq_status` atomic. When an IRQ fires, the platform
/// calls [`handle_interrupt()`], usually through [`RknpuIrqHandler`]. That
/// reads `INTERRUPT_STATUS`, clears the hardware interrupt, and publishes the
/// fuzzed status into `irq_status`. The submit path can then watch the atomic
/// instead of polling MMIO registers in a tight loop.
pub struct RknpuCore {
    base: NonNull<u8>,
    pub(crate) core_slot: u8,
    /// Shared interrupt-status shadow written by IRQ handling and read by
    /// submit-side wait loops.
    pub(crate) irq_status: Arc<AtomicU32>,
}
unsafe impl Send for RknpuCore {}

impl RknpuCore {
    /// Program and launch exactly one task on this hardware core.
    pub fn start_execute_one(
        &mut self,
        idx: usize,
        data: &RknpuData,
        rknpu_task: &mut RknpuTask,
        submit_flags: u32,
        task_dma_addr: u64,
    ) -> Result<(), RknpuError> {
        let job = SubmitRef {
            base: SubmitBase {
                flags: JobMode::from_bits_retain(submit_flags),
                task_array_dma_address: task_dma_addr as _,
                core_idx: idx,
                // Wait for the LAST task's interrupt (pipeline completion)
                int_mask: rknpu_task.int_mask,
                int_clear: rknpu_task.int_mask,
                regcfg_amount: rknpu_task.regcfg_amount,
            },
            task_number: 1,
            regcmd_base_addr: rknpu_task.regcmd_addr as _,
        };
        debug!(
            "[NPU] core{} start_execute_one task_array_dma_address={:#x} regcmd_base={:#x} regcfg_amount={} int_mask={:#x} flags={:#x}",
            idx,
            task_dma_addr,
            job.regcmd_base_addr,
            job.base.regcfg_amount,
            job.base.int_mask,
            submit_flags
        );
        debug!(
            "[NPU]   batch: {} tasks, regcmd@{:#x}, {} regcfg_words, int_mask={:#x}",
            1, job.regcmd_base_addr, job.base.regcfg_amount, job.base.int_mask
        );
        debug!("Submit {} jobs: {job:#x?}", 1);

        // Clear the shared atomic before submitting — so we only see
        // status bits from THIS submission, not leftovers.
        self.irq_status.store(0, Ordering::Release);

        // Program PC registers and start execution
        debug!("Submitting PC job...");
        self.submit_pc(data, &job).unwrap();
        debug!(
            "[NPU] core{} start_execute_one submitted operation_enable pulse for regcmd_base={:#x}",
            idx, job.regcmd_base_addr
        );
        Ok(())
    }

    /// Submit a batch of tasks to a single NPU core and wait for completion.
    ///
    /// `idx` is both the `subcore_task[]` index and the physical core index.
    ///
    /// # Completion modes
    ///
    /// - **IRQ-driven** (`wait_fn = Some`)`: the CPU sleeps between checks. When
    ///   the NPU finishes, the IRQ handler calls `handle_interrupt()`, stores
    ///   the fuzzed status into `irq_status`, and the loop exits on the next
    ///   wake-up.
    ///
    /// - **Busy-polling** (`wait_fn = None`): the CPU reads
    ///   `INTERRUPT_STATUS` directly in a tight loop. Simple, but wasteful.
    ///
    /// # Batching
    ///
    /// The hardware accepts at most `max_submit_number` tasks per batch. If the
    /// submit range is larger, this function loops and waits for each batch in
    /// turn.
    pub fn _submit_one(
        &mut self,
        data: &RknpuData,
        wait_fn: Option<fn()>,
        idx: usize,
        args: &mut RknpuSubmit,
    ) -> Result<usize, RknpuError> {
        let task_ptr = args.task_array_cpu_address as *mut RknpuTask;
        let subcore = &args.subcore_task[idx];

        let mut task_iter = subcore.task_start as usize;
        let task_iter_end = task_iter + subcore.task_number as usize;
        let max_submit_number = data.max_submit_number as usize;

        while task_iter < task_iter_end {
            // Clamp batch size to hardware limit
            let task_number = (task_iter_end - task_iter).min(max_submit_number);
            let submit_tasks =
                unsafe { core::slice::from_raw_parts_mut(task_ptr.add(task_iter), task_number) };

            // Build the register-level submission descriptor
            let job = SubmitRef {
                base: SubmitBase {
                    flags: JobMode::from_bits_retain(args.flags),
                    task_array_dma_address: args.task_array_dma_address as _,
                    core_idx: idx,
                    // Wait for the LAST task's interrupt (pipeline completion)
                    int_mask: submit_tasks.last().unwrap().int_mask,
                    int_clear: submit_tasks[0].int_mask,
                    regcfg_amount: submit_tasks[0].regcfg_amount,
                },
                task_number,
                regcmd_base_addr: submit_tasks[0].regcmd_addr as _,
            };
            debug!(
                "[NPU]   batch: {} tasks, regcmd@{:#x}, {} regcfg_words, int_mask={:#x}",
                task_number, job.regcmd_base_addr, job.base.regcfg_amount, job.base.int_mask
            );
            debug!("Submit {task_number} jobs: {job:#x?}");

            // Drain any leftover interrupts from previous execution
            while self.handle_interrupt() != 0 {
                spin_loop();
            }

            // Clear the shared atomic before submitting — so we only see
            // status bits from THIS submission, not leftovers.
            self.irq_status.store(0, Ordering::Release);

            // Program PC registers and start execution
            debug!("Submitting PC job...");
            self.submit_pc(data, &job).unwrap();

            // ── Wait for completion ──────────────────────────────────────
            let int_status = if let Some(wait) = wait_fn {
                debug!("[NPU]   waiting (IRQ+WFI mode)...");
                // ┌─────────────────────────────────────────────────────┐
                // │  IRQ-driven mode (CPU sleeps between checks)        │
                // │                                                     │
                // │  NPU runs → fires IRQ → handler calls               │
                // │  handle_interrupt() → stores fuzzed status to       │
                // │  irq_status atomic → CPU wakes from WFI → we       │
                // │  read the atomic here and proceed.                  │
                // └─────────────────────────────────────────────────────┘
                loop {
                    let status = self.irq_status.load(Ordering::Acquire);
                    if status & job.base.int_mask > 0 {
                        break job.base.int_mask & status;
                    }
                    if status != 0 {
                        debug!("Unexpected IRQ status: {:#x}", status);
                        return Err(RknpuError::TaskError);
                    }
                    // Sleep until any interrupt (including NPU) wakes the CPU.
                    (wait)();
                }
            } else {
                // ┌─────────────────────────────────────────────────────┐
                // │  Legacy busy-poll mode (direct MMIO register read)  │
                // │                                                     │
                // │  CPU spins reading INTERRUPT_STATUS until the       │
                // │  expected bits appear.  Simple but wastes cycles.   │
                // └─────────────────────────────────────────────────────┘
                loop {
                    let status = self.pc().interrupt_status().read().bits();
                    let status = rknpu_fuzz_status(status);
                    if status & job.base.int_mask > 0 {
                        break job.base.int_mask & status;
                    }
                    if status != 0 {
                        debug!("Interrupt status changed: {:#x}", status);
                        return Err(RknpuError::TaskError);
                    }
                }
            };

            // Acknowledge the interrupt and advance to next batch.
            // In IRQ mode the handler already cleared the HW interrupt,
            // but we still clear once more to be safe.
            self.clean_interrupts();
            // Reset atomic for the next batch.
            self.irq_status.store(0, Ordering::Release);
            debug!("[NPU]   batch done: int_status={:#x}", int_status);
            submit_tasks.last_mut().unwrap().int_status = int_status;
            task_iter += task_number;
        }

        Ok(subcore.task_number as usize)
    }

    /// # Safety
    ///
    /// The caller must guarantee that `base_addr` points to a valid mapped RKNN
    /// register window and stays alive for the lifetime of the returned object.
    pub unsafe fn new(base_addr: NonNull<u8>, core_slot: u8) -> Self {
        Self {
            base: base_addr,
            core_slot,
            irq_status: Arc::new(AtomicU32::new(0)),
        }
    }

    #[inline(always)]
    pub(crate) fn offset_ptr<T>(&self, offset: usize) -> NonNull<T> {
        // Safety: the caller guarantees the MMIO mapping is valid and the
        // offsets come from documented register layouts.
        unsafe {
            let ptr = self.base.as_ptr().add(offset);
            NonNull::new_unchecked(ptr as *mut T)
        }
    }

    #[inline(always)]
    fn reg<T>(&self, offset: usize) -> &T {
        unsafe { self.offset_ptr::<T>(offset).as_ref() }
    }

    pub fn pc(&self) -> &rknpu_regs::pc::RegisterBlock {
        self.reg(rknpu_regs::Pc::PTR as usize)
    }

    pub fn cna(&self) -> &rknpu_regs::cna::RegisterBlock {
        self.reg(rknpu_regs::Cna::PTR as usize)
    }

    pub fn mac(&self) -> &rknpu_regs::mac::RegisterBlock {
        self.reg(rknpu_regs::Mac::PTR as usize)
    }

    pub fn dpu(&self) -> &rknpu_regs::dpu::RegisterBlock {
        self.reg(rknpu_regs::Dpu::PTR as usize)
    }

    pub fn dpu_rdma(&self) -> &rknpu_regs::dpu_rdma::RegisterBlock {
        self.reg(rknpu_regs::DpuRdma::PTR as usize)
    }

    pub fn ppu(&self) -> &rknpu_regs::ppu::RegisterBlock {
        self.reg(rknpu_regs::Ppu::PTR as usize)
    }

    pub fn ppu_rdma(&self) -> &rknpu_regs::ppu_rdma::RegisterBlock {
        self.reg(rknpu_regs::PpuRdma::PTR as usize)
    }

    pub fn ddma(&self) -> &rknpu_regs::ddma::RegisterBlock {
        self.reg(rknpu_regs::Ddma::PTR as usize)
    }

    pub fn sdma(&self) -> &rknpu_regs::sdma::RegisterBlock {
        self.reg(rknpu_regs::Sdma::PTR as usize)
    }

    pub fn global(&self) -> &rknpu_regs::global::RegisterBlock {
        self.reg(rknpu_regs::Global::PTR as usize)
    }

    pub fn version(&self) -> u32 {
        self.pc()
            .version()
            .read()
            .bits()
            .wrapping_add(self.pc().version_num().read().bits() & 0xffff)
    }

    pub fn clean_interrupts(&self) {
        self.pc()
            .interrupt_clear()
            .write(|w| unsafe { w.bits(INT_CLEAR_ALL) });
    }

    pub(crate) fn submit_pc(
        &mut self,
        config: &RknpuData,
        args: &SubmitRef,
    ) -> Result<(), RknpuError> {
        let pc_data_amount_scale = config.pc_data_amount_scale;

        self.pc().base_address().write(|w| unsafe { w.bits(1) });

        let task_pp_en = if args.base.flags.contains(JobMode::PINGPONG) {
            1
        } else {
            0
        };
        let pc_task_number_bits = config.pc_task_number_bits;

        if config.irqs.get(args.base.core_idx).is_some() {
            let val = 0xe + 0x10000000 * args.base.core_idx as u32;

            debug!("Set PC S_POINTER to {:#x}", val);

            self.cna().s_pointer().write(|w| unsafe { w.bits(val) });
            self.mac().s_pointer().write(|w| unsafe { w.bits(val) });
        }

        let pc_base_addr = args.regcmd_base_addr;

        debug!("Set PC BASE_ADDRESS to {:#x}", pc_base_addr);

        self.pc()
            .base_address()
            .write(|w| unsafe { w.bits(pc_base_addr) });

        let amount = (args.base.regcfg_amount + RKNPU_PC_DATA_EXTRA_AMOUNT)
            .div_ceil(pc_data_amount_scale)
            - 1;

        debug!("Set PC REGISTER_AMOUNTS to {:#x}", amount);

        self.pc()
            .register_amounts()
            .write(|w| unsafe { w.bits(amount) });

        self.pc()
            .interrupt_mask()
            .write(|w| unsafe { w.bits(args.base.int_mask) });
        self.pc()
            .interrupt_clear()
            .write(|w| unsafe { w.bits(args.base.int_clear) });
        let task_number = args.task_number as u32;

        let task_control = ((0x6 | task_pp_en) << pc_task_number_bits) | task_number;
        debug!("Set PC TASK_CONTROL to {:#x}", task_control);
        self.pc()
            .task_con()
            .write(|w| unsafe { w.bits(task_control) });
        debug!(
            "Set PC task_array_dma_address_ADDR to {:#x}",
            args.base.task_array_dma_address
        );
        self.pc()
            .task_dma_base_addr()
            .write(|w| unsafe { w.bits(args.base.task_array_dma_address) });
        mb();
        self.pc().operation_enable().write(|w| unsafe { w.bits(1) });
        mb();
        self.pc().operation_enable().write(|w| unsafe { w.bits(0) });

        debug!("Submitted {args:#x?}");

        Ok(())
    }

    pub fn submit(
        &mut self,
        config: &RknpuData,
        wait_fn: Option<fn()>,
        args: &mut Submit,
    ) -> Result<(), RknpuError> {
        let max_submit_number = config.max_submit_number as usize;
        let regcfg_amount = args.base.regcfg_amount as usize;
        let total_tasks = args.tasks.len();
        let regcmd_base_addr = args.regcmd_all.bus_addr();

        let mut task_iter = 0usize;
        while task_iter < total_tasks {
            let task_number = (total_tasks - task_iter).min(max_submit_number);
            let batch_offset_bytes = task_iter
                .saturating_mul(regcfg_amount)
                .saturating_mul(core::mem::size_of::<u64>());
            let batch_regcmd_addr = regcmd_base_addr.saturating_add(batch_offset_bytes as u64);
            if batch_regcmd_addr > u32::MAX as u64 {
                return Err(RknpuError::InvalidParameter);
            }

            let job = SubmitRef {
                base: args.base.clone(),
                task_number,
                regcmd_base_addr: batch_regcmd_addr as u32,
            };

            self.drain_pending_interrupts();
            self.irq_status.store(0, Ordering::Release);
            self.submit_pc(config, &job)?;

            let int_status = if let Some(wait) = wait_fn {
                loop {
                    let status = self.irq_status.load(Ordering::Acquire);
                    if status & job.base.int_mask > 0 {
                        break job.base.int_mask & status;
                    }
                    if status != 0 {
                        debug!("Unexpected IRQ status: {:#x}", status);
                        return Err(RknpuError::TaskError);
                    }
                    (wait)();
                }
            } else {
                loop {
                    let status = self.pc().interrupt_status().read().bits();
                    let status = rknpu_fuzz_status(status);
                    if status & job.base.int_mask > 0 {
                        break job.base.int_mask & status;
                    }
                    if status != 0 {
                        debug!("Interrupt status changed: {:#x}", status);
                        return Err(RknpuError::TaskError);
                    }
                }
            };

            self.clean_interrupts();
            self.irq_status.store(0, Ordering::Release);
            debug!(
                "[NPU] high-level submit batch done task_start={} task_number={} int_status={:#x}",
                task_iter, task_number, int_status
            );
            task_iter += task_number;
        }

        Ok(())
    }

    /// Drain leftover pending interrupts before rebinding this core to new work.
    ///
    /// Without this step, a stale interrupt from the previous batch could be
    /// misattributed to the new dispatch.
    pub fn drain_pending_interrupts(&self) {
        while self.handle_interrupt() != 0 {
            self.irq_status.store(0, Ordering::Release);
            spin_loop();
        }
        self.irq_status.store(0, Ordering::Release);
    }

    /// Read `INTERRUPT_STATUS`, clear the hardware interrupt, and publish the
    /// fuzzed result into the shared `irq_status` atomic.
    ///
    /// Called from two places:
    /// - the IRQ handler path, via `RknpuIrqHandler::handle`
    /// - the submit-side drain loop before a new dispatch starts
    ///
    /// Returns the fuzzed status. Any non-zero value means something completed
    /// or faulted.
    pub fn handle_interrupt(&self) -> u32 {
        let int_status = self.pc().interrupt_status().read().bits();
        mb();
        self.pc()
            .interrupt_clear()
            .write(|w| unsafe { w.bits(INT_CLEAR_ALL) });
        let fuzzed = rknpu_fuzz_status(int_status);

        if fuzzed != 0 {
            debug!(
                "[NPU] IRQ core{} raw_status={:#x} fuzzed={:#x}",
                self.core_slot, int_status, fuzzed
            );
            // Publish the status so the waiting submit path can observe it
            // without polling MMIO directly.
            self.irq_status.fetch_or(fuzzed, Ordering::Release);
        }
        fuzzed
    }

    fn write_mmio_u32(&self, offset: u16, value: u32) {
        unsafe {
            self.offset_ptr::<u32>(offset as usize)
                .as_ptr()
                .write_volatile(value)
        }
    }
}

#[inline(always)]
pub fn rknpu_fuzz_status(status: u32) -> u32 {
    let mut fuzz_status = 0;
    if (status & 0x3) != 0 {
        fuzz_status |= 0x3;
    }
    if (status & 0xc) != 0 {
        fuzz_status |= 0xc;
    }
    if (status & 0x30) != 0 {
        fuzz_status |= 0x30;
    }
    if (status & 0xc0) != 0 {
        fuzz_status |= 0xc0;
    }
    if (status & 0x300) != 0 {
        fuzz_status |= 0x300;
    }
    if (status & 0xc00) != 0 {
        fuzz_status |= 0xc00;
    }
    fuzz_status
}

#[cfg(test)]
mod tests {
    use super::*;

    const FAKE_MMIO_LEN: usize = 0x10000;

    fn build_fake_core() -> (RknpuCore, Vec<u8>) {
        let mut mmio = vec![0_u8; FAKE_MMIO_LEN];
        let core = unsafe { RknpuCore::new(NonNull::new(mmio.as_mut_ptr()).unwrap(), 0) };
        (core, mmio)
    }

    #[test]
    fn handle_interrupt_without_binding_only_publishes_irq_status() {
        let (core, _mmio) = build_fake_core();
        core.write_mmio_u32(PC_INTERRUPT_STATUS_OFFSET, 0x200);

        let fuzzed = core.handle_interrupt();

        assert_eq!(fuzzed, 0x300);
        assert_eq!(core.irq_status.load(Ordering::Acquire), 0x300);
    }

    #[test]
    fn handle_interrupt_accumulates_fuzzed_status_in_atomic() {
        let (core, _mmio) = build_fake_core();
        core.write_mmio_u32(PC_INTERRUPT_STATUS_OFFSET, 0x300);

        let fuzzed = core.handle_interrupt();

        assert_eq!(fuzzed, 0x300);
        assert_eq!(core.irq_status.load(Ordering::Acquire), 0x300);
    }

    #[test]
    fn handle_interrupt_keeps_accumulating_until_harvest_clears_it() {
        let (core, _mmio) = build_fake_core();
        core.irq_status.store(0x100, Ordering::Release);
        core.write_mmio_u32(PC_INTERRUPT_STATUS_OFFSET, 0x300);

        let fuzzed = core.handle_interrupt();

        assert_eq!(fuzzed, 0x300);
        assert_eq!(core.irq_status.load(Ordering::Acquire), 0x300);
    }
}
