#![doc = "Peripheral access API for RK3588_NPU microcontrollers (generated using svd2rust v0.37.1 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.1/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_cfg))]
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[doc = "CNA register block"]
pub type Cna = crate::Periph<cna::RegisterBlock, 0x1000>;
impl core::fmt::Debug for Cna {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cna").finish()
    }
}
#[doc = "CNA register block"]
pub mod cna;
#[doc = "DDMA register block"]
pub type Ddma = crate::Periph<ddma::RegisterBlock, 0x8000>;
impl core::fmt::Debug for Ddma {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ddma").finish()
    }
}
#[doc = "DDMA register block"]
pub mod ddma;
#[doc = "DPU register block"]
pub type Dpu = crate::Periph<dpu::RegisterBlock, 0x4000>;
impl core::fmt::Debug for Dpu {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dpu").finish()
    }
}
#[doc = "DPU register block"]
pub mod dpu;
#[doc = "DPU_RDMA register block"]
pub type DpuRdma = crate::Periph<dpu_rdma::RegisterBlock, 0x5000>;
impl core::fmt::Debug for DpuRdma {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("DpuRdma").finish()
    }
}
#[doc = "DPU_RDMA register block"]
pub mod dpu_rdma;
#[doc = "GLOBAL register block"]
pub type Global = crate::Periph<global::RegisterBlock, 0xf000>;
impl core::fmt::Debug for Global {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Global").finish()
    }
}
#[doc = "GLOBAL register block"]
pub mod global;
#[doc = "MAC register block"]
pub type Mac = crate::Periph<mac::RegisterBlock, 0x3000>;
impl core::fmt::Debug for Mac {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Mac").finish()
    }
}
#[doc = "MAC register block"]
pub mod mac;
#[doc = "PC register block"]
pub type Pc = crate::Periph<pc::RegisterBlock, 0>;
impl core::fmt::Debug for Pc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pc").finish()
    }
}
#[doc = "PC register block"]
pub mod pc;
#[doc = "PPU register block"]
pub type Ppu = crate::Periph<ppu::RegisterBlock, 0x6000>;
impl core::fmt::Debug for Ppu {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ppu").finish()
    }
}
#[doc = "PPU register block"]
pub mod ppu;
#[doc = "PPU_RDMA register block"]
pub type PpuRdma = crate::Periph<ppu_rdma::RegisterBlock, 0x7000>;
impl core::fmt::Debug for PpuRdma {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PpuRdma").finish()
    }
}
#[doc = "PPU_RDMA register block"]
pub mod ppu_rdma;
#[doc = "SDMA register block"]
pub type Sdma = crate::Periph<sdma::RegisterBlock, 0x9000>;
impl core::fmt::Debug for Sdma {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sdma").finish()
    }
}
#[doc = "SDMA register block"]
pub mod sdma;
#[no_mangle]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "CNA"]
    pub cna: Cna,
    #[doc = "DDMA"]
    pub ddma: Ddma,
    #[doc = "DPU"]
    pub dpu: Dpu,
    #[doc = "DPU_RDMA"]
    pub dpu_rdma: DpuRdma,
    #[doc = "GLOBAL"]
    pub global: Global,
    #[doc = "MAC"]
    pub mac: Mac,
    #[doc = "PC"]
    pub pc: Pc,
    #[doc = "PPU"]
    pub ppu: Ppu,
    #[doc = "PPU_RDMA"]
    pub ppu_rdma: PpuRdma,
    #[doc = "SDMA"]
    pub sdma: Sdma,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            cna: Cna::steal(),
            ddma: Ddma::steal(),
            dpu: Dpu::steal(),
            dpu_rdma: DpuRdma::steal(),
            global: Global::steal(),
            mac: Mac::steal(),
            pc: Pc::steal(),
            ppu: Ppu::steal(),
            ppu_rdma: PpuRdma::steal(),
            sdma: Sdma::steal(),
        }
    }
}
