name: Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许 Action 写入 gh-pages 分支
    steps:
      - uses: actions/checkout@v4

      - name: Install mdBook
        run: |
          mkdir mdbook
          curl -L https://github.com/rust-lang/mdBook/releases/download/v0.4.37/mdbook-v0.4.37-x86_64-unknown-linux-gnu.tar.gz | tar -xz -C mdbook
          echo "$PWD/mdbook" >> $GITHUB_PATH

      - name: Build Book
        run: mdbook build docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book # mdbook 默认输出目录
